name = "potacademy-workers"
main = "workers/src/index.js"
compatibility_date = "2024-08-01"

[[d1_databases]]
binding = "DB"
database_name = "potacademy-db"
database_id = "00d93476-e0cf-4454-b5a1-8ab233d111dd"

[[r2_buckets]]
binding = "R2_BUCKET"
bucket_name = "potacademy-files"

[vars]
JWT_SECRET = "your-super-secret-jwt-key-change-this-in-production"
TEACHER_INVITE_CODE = "TEACHER2024"
STUDENT_INVITE_CODE = "STUDENT2024"
OPENAI_API_KEY = "your-openai-key"
DASHSCOPE_API_KEY = "your-qwen-key"